Huh
3arthqu4ke/phobot pull request #3
Opened 2023-12-23 09:42 UTC by GurteX

Why is it like that

2023-12-23 17:01 UTC, cattyngmd requested changes
it would be better if u check for blocks hardness instead

2023-12-23 17:30 UTC, 3arthqu4ke commented
See Speedmine

2023-12-23 21:19 UTC, GurteX commented
Wow its a quick fix man, just this

2023-12-24 22:18 UTC, 3arthqu4ke commented
Nono this Enterprise Software has no place for, to use your words "quick fixes"! 🤓

2023-12-24 22:18 UTC, 3arthqu4ke commented
Also U get the blockstate twice here

2023-12-30 04:18 UTC, GurteX commented
> Also U get the blockstate twice here

Bad bait considering that you didnt think of this b4

2023-12-30 11:26 UTC, 3arthqu4ke requested changes

2023-12-30 11:26 UTC, 3arthqu4ke commented on src/main/java/me/earth/phobot/services/BlockDestructionService.java
> +                    PingBypassApi.getEventBus().post(new FriendStartBlockMineEvent(p));
What is a FriendStartBlockMineEvent? This wont compile.

2023-12-30 11:26 UTC, 3arthqu4ke commented on src/main/java/me/earth/phobot/services/BlockDestructionService.java
> +        return state.getDestroySpeed(level, pos) < 0 && !state.isAir();
Condition is wrong destroyspeed < 0 means the Block is Not breakable.

2023-12-30 11:44 UTC, GurteX commented
oops lol i didnt see that other event my bad g

2023-12-30 11:48 UTC, GurteX commented
im never writing shi on github instead of an ide again

2024-01-07 14:29 UTC, 3arthqu4ke requested changes

2024-01-07 14:29 UTC, 3arthqu4ke commented on src/main/java/me/earth/phobot/services/BlockDestructionService.java
> +        return state.getDestroySpeed(level, pos) > 0 && !state.isAir();
```java
return state.getDestroySpeed(level, pos) >= 0 && !state.isAir();
```

2024-01-07 14:32 UTC, 3arthqu4ke commented on src/main/java/me/earth/phobot/services/BlockDestructionService.java
> +        return state.getDestroySpeed(level, pos) > 0 && !state.isAir();
Also fix build

2024-01-07 15:47 UTC, GurteX commented on src/main/java/me/earth/phobot/services/BlockDestructionService.java
> +        return state.getDestroySpeed(level, pos) > 0 && !state.isAir();
> ```java
> return state.getDestroySpeed(level, pos) >= 0 && !state.isAir();
> ```

Is 0 a valid destroy speed

2024-01-07 15:47 UTC, GurteX commented on src/main/java/me/earth/phobot/services/BlockDestructionService.java
> +        return state.getDestroySpeed(level, pos) > 0 && !state.isAir();
> Also fix build

what build do you want me to fix ???

2024-01-11 11:15 UTC, GurteX commented
mf went on dem holidays neva coming back

2024-01-13 08:35 UTC, GurteX commented
Bro

2024-01-13 20:06 UTC, 3arthqu4ke approved these changes
You did it!

2024-01-13 20:24 UTC, GurteX commented
> You did it!

Real

2024-01-13 21:31 UTC, merged